# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easi6-project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   use_frameworks!
   
    pod 'Alamofire'
    pod 'SwiftLint'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SnapKit', '~>5.0.0'

  # Pods for easi6-project

  target 'easi6-projectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
