# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'FIneDust' do

  inhibit_all_warnings!

  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.7' 
end
